version: '3'

services:
  django:
    build:
      context: ./django_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./django_service:/djangoapp
    command: >
      sh -c "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - ecommerce-db

  fastapi:
    build:
      context: ./fastapi_service
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - ./fastapi_service:/fastapp
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8050 --reload"

    depends_on:
      - ecommerce-db

  ecommerce-db:
    container_name: ecommerce-db
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
